model:
  name: DefectClassifier
  model_path: /Users/ekaterina/PycharmProjects/Binary-Classification-with-Software-Defects-Dataset/models/best_model-v27.ckpt
  scaler_path: data/processed/scaler.joblib
  input_size: 21
  hidden_sizes:
  - 64
  - 32
  - 16
  dropout_rate: 0.3
  learning_rate: 0.001
  label_smoothing: 0.1
  use_focal_loss: true
  focal_gamma: 2.0
  batch_size: 32
  num_classes: 2
  onnx_model_path: models/onnx/model.onnx
  include_preprocess: false
  opset_version: 13
